### ISSUE TITLE
Registering new type handlers for PlayerActions outside of the dialogs module has no effect

### ISSUE THREAD

**Issue by CptCrispyCrunchy** [Terasology/Dialogs#2]
The engine uses the `PlayerActionTypeHandler` instead for serialization. Deleting it resolves the problem.
Is it even used?

**Comment by msteiger** [comment]
As far as I remember I used it in Light & Shadow to enable the player to choose from a list of options in the dialog conversation. What exactly is the problem here?

**Comment by CptCrispyCrunchy** [comment]
I tried to register a typehandler for my own implementation of a PlayerAction (an action for showing my market screen). However the engine didn't look for my typehandler when serializing, instead it used the  `PlayerActionTypeHandler` interface (which does nothing despite throwing an error msg and NPE).
