### ISSUE TITLE
Fixes for new Terasology serialization system (engine PR 3535)

### ISSUE THREAD

**Issue by Cervator** [Terasology/Dialogs#8]
The new serialization system introduced by MovingBlocks/Terasology#3535 (tracking branch [`MovingBlocks/newSerialization`](https://github.com/MovingBlocks/Terasology/tree/newSerialization)) causes this module to no longer compile. Only 4 classes (the `TypeHandler` implementations in `org.terasology.dialogs.action`) are affected and the changes seem fairly straight forward - although I'm not sure if any issues will result after.

Current users of Dialogs include LightAndShadow (the NPC on the spawn platform) and TutorialDynamicCities (vaguely recall a market screen you can trigger from an NPC in a specific building?). Both naturally thus won't work either, but could be useful for testing when also fixed.

Sending this @eviltak's way as the author of the engine PR and/or to @dacharya64 / @Naman-sopho in case either of them have a chance to check it out :-)

For previous reverted fixes (may be less relevant with later changes to the serialization system), see 3b5804e.

**Comment by Cervator** [comment]
Note: This is now tied to https://github.com/MovingBlocks/Terasology/issues/3490 instead - see it for details

**Comment by eviltak** [comment]
Now tracked by PR MovingBlocks/Terasology#3535.
